execute as @a[scores={star=0..20}] run function star:star/main/part0
execute as @a[scores={star=20..40}] run function star:star/main/part1
execute as @a[scores={star=40..60}] run function star:star/main/part2
execute as @a[scores={star=60..80}] run function star:star/main/part3
execute as @a[scores={star=80..100}] run function star:star/main/part4
execute as @a[scores={star=100..120}] run function star:star/main/part5
execute as @a[scores={star=120..140}] run function star:star/main/part6
execute as @a[scores={star=140..160}] run function star:star/main/part7
execute as @a[scores={star=160..180}] run function star:star/main/part8
execute as @a[scores={star=180..200}] run function star:star/main/part9
execute as @a[scores={star=200..220}] run function star:star/main/part10
execute as @a[scores={star=220..240}] run function star:star/main/part11
execute as @a[scores={star=240..260}] run function star:star/main/part12
execute as @a[scores={star=260..280}] run function star:star/main/part13
execute as @a[scores={star=280..300}] run function star:star/main/part14
execute as @a[scores={star=300..320}] run function star:star/main/part15
execute as @a[scores={star=320..340}] run function star:star/main/part16
execute as @a[scores={star=340..360}] run function star:star/main/part17
scoreboard players add @a star 1
